/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoanPackage;


/**
 *
 * @author USER
 */

public class LoanApp extends javax.swing.JFrame implements LoanConstants {
    
    public static int current = 0;
    public static final int i = 100;
    public static Loan[] list;
    public static int[] type;
    private float currRate;
    
    public LoanApp() {
        initComponents();
        list = new Loan[i];
        type = new int[i];
        
    }
    
    private boolean containsDigits(String str) {
    for (char c : str.toCharArray()) {
        if (Character.isDigit(c)) {
            return true;
        }
    }
    return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CurrentPrimeValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LoanNumberValue = new javax.swing.JTextField();
        LastNameValue = new javax.swing.JTextField();
        LoanAmountValue = new javax.swing.JTextField();
        TermComboBox = new javax.swing.JComboBox<>();
        LoanTypeComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ViewComboBox = new javax.swing.JComboBox<>();
        GoBttn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaValue = new javax.swing.JTextArea();
        SaveBttn = new javax.swing.JButton();
        ClearBttn = new javax.swing.JButton();
        ExitBttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Current Prime Rate");

        CurrentPrimeValue.setBackground(new java.awt.Color(204, 204, 255));
        CurrentPrimeValue.setDisabledTextColor(new java.awt.Color(255, 153, 153));
        CurrentPrimeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentPrimeValueActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Loan Number");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Last Name");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Loan amount");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Term");

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Loan Type");

        LoanNumberValue.setBackground(new java.awt.Color(204, 204, 255));

        LastNameValue.setBackground(new java.awt.Color(204, 204, 255));

        LoanAmountValue.setBackground(new java.awt.Color(204, 204, 255));

        TermComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--  Select --", "Short Term", "Medium Term", "Long Term" }));
        TermComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TermComboBoxActionPerformed(evt);
            }
        });

        LoanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Business", "Personal" }));

        jLabel7.setText("What do you want to view?");

        ViewComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "All Loans", "All Personal Loans", "All Business Loans", "A Particular Loan" }));
        ViewComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewComboBoxActionPerformed(evt);
            }
        });

        GoBttn.setText("Go");
        GoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBttnActionPerformed(evt);
            }
        });

        TextAreaValue.setEditable(false);
        TextAreaValue.setBackground(new java.awt.Color(255, 255, 204));
        TextAreaValue.setColumns(20);
        TextAreaValue.setRows(5);
        jScrollPane1.setViewportView(TextAreaValue);

        SaveBttn.setText("Save");
        SaveBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBttnActionPerformed(evt);
            }
        });

        ClearBttn.setText("Clear");
        ClearBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBttnActionPerformed(evt);
            }
        });

        ExitBttn.setText("Exit");
        ExitBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBttnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Sanchez Construction Loan Co.");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoanAmountValue)
                            .addComponent(CurrentPrimeValue)
                            .addComponent(LoanNumberValue)
                            .addComponent(LastNameValue)
                            .addComponent(TermComboBox, 0, 1, Short.MAX_VALUE)
                            .addComponent(LoanTypeComboBox, 0, 96, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(GoBttn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(SaveBttn)
                        .addGap(39, 39, 39)
                        .addComponent(ClearBttn)
                        .addGap(57, 57, 57)
                        .addComponent(ExitBttn)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(380, 380, 380))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentPrimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ViewComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(GoBttn)
                                .addComponent(jLabel7)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LoanNumberValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoanAmountValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TermComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LoanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBttn)
                    .addComponent(ClearBttn)
                    .addComponent(ExitBttn))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBttnActionPerformed
        // TODO add your handling code here:
        int choice = jPane.showConfirmDialog(rootPane,"Are you sure?", "Confirm Exit", jPane.YES_NO_OPTION);
        if(choice == jPane.YES_OPTION){
            System.exit(0);  
        }
        
    }//GEN-LAST:event_ExitBttnActionPerformed

    private void ClearBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBttnActionPerformed
        // TODO add your handling code here:
        //CurrentPrimeValue.setText("");
        LoanNumberValue.setText("");
        LastNameValue.setText("");
        LoanAmountValue.setText("");
        TextAreaValue.setText("");
        TermComboBox.setSelectedIndex(0);
        LoanTypeComboBox.setSelectedIndex(0);
        ViewComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_ClearBttnActionPerformed

    private void GoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBttnActionPerformed
        // TODO add your handling code here:
 //        try{
            if(ViewComboBox.getSelectedItem() == "All Loans"){
                try{
                int found = 0;
           // TextAreaValue.setText("Loan Number\tLast Name\tLoan Amount\tInterest Rate\tTerm\tAmount Due");
            TextAreaValue.setText("********** ALL LOANS **********");
             for(int i = 0; i < list.length; i++) {
                if(list[i] instanceof PersonalLoan || list[i] instanceof BusinessLoan) {
            TextAreaValue.append("\n" + list[i].toString());
                if(list[i] instanceof PersonalLoan) {
            TextAreaValue.append("Loan Type: Personal Loan\n");
            } else if (list[i] instanceof BusinessLoan) {
            TextAreaValue.append("Loan Type: Business Loan\n");
        }
        found++;
    }
}
                    if(found == 0){
                    jPane.showMessageDialog(rootPane, "No loans found.");
                    }
                }catch(NullPointerException npe){
                    jPane.showMessageDialog(rootPane, "No loans found.");
                }
            }else if(ViewComboBox.getSelectedItem() == "All Personal Loans"){
                //TextAreaValue.setText("Loan Number\tLast Name\tLoan Amount\tInterest Rate\tTerm\tAmount Due");
                TextAreaValue.setText("************ PERSONAL LOANS ************");
                int persCount = 0;
                for(int i = 0; i<list.length;i++){
                    if(list[i] instanceof PersonalLoan){
                    TextAreaValue.append("\n"+list[i].toString());
                    persCount++;
                    }
                }
                if(persCount == 0){
                    jPane.showMessageDialog(rootPane, "No loans found.");
                }
            }else if(ViewComboBox.getSelectedItem() == "All Business Loans"){
                
                //TextAreaValue.setText("Loan Number\tLast Name\tLoan Amount\tInterest Rate\tTerm\tAmount Due");
                TextAreaValue.setText("************ BUSINESS LOANS ************");
                int busiCount = 0;
                for(int i = 0; i<list.length;i++){
                    if(list[i] instanceof BusinessLoan){
                    TextAreaValue.append("\n"+list[i].toString());
                    busiCount++;
                    }
                }
                if(busiCount == 0){
                    jPane.showMessageDialog(rootPane, "No loans found.");
                }
            }else if(ViewComboBox.getSelectedItem() == "A Particular Loan"){
                try{
                    int found = 0;
                    int number = Integer.parseInt(jPane.showInputDialog("Input Loan Number: "));
                    //TextAreaValue.setText("Loan Number\tLast Name\tLoan Amount\tInterest Rate\tTerm\tAmount Due");
                    TextAreaValue.setText("************ A PARTICULAR LOAN ************");
                    try{
                       for(int i = 0; i<list.length;i++){
                        if(list[i] instanceof PersonalLoan || list[i] instanceof BusinessLoan){
                            if(list[i].getLoanNumber()==number){
                            TextAreaValue.append("\n"+list[i].toString());
                            if(list[i] instanceof PersonalLoan) {
                            TextAreaValue.append("Loan Type: Personal Loan\n");
                            } else if (list[i] instanceof BusinessLoan) {
                            TextAreaValue.append("Loan Type: Business Loan\n");
                               }
                            found++;
                            } 
                        }  
                    }
                       if(found == 0){
                            jPane.showMessageDialog(rootPane, "Loan number does not exist!");
                            }
                    }catch(NullPointerException npe){
                        jPane.showMessageDialog(rootPane, "No Loans yet.");
                    }
                }catch(NumberFormatException npe){
                    jPane.showMessageDialog(rootPane, "No loan number was inputted.");
                }
            }else{
                jPane.showMessageDialog(rootPane, "Please select an option.");
            }
//        }
//        catch(Exception e){
//            System.out.println("These are all the loans.");
//        }
    }//GEN-LAST:event_GoBttnActionPerformed

    private void CurrentPrimeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentPrimeValueActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CurrentPrimeValueActionPerformed

    private void SaveBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBttnActionPerformed
        // TODO add your handling code here:
        int lNumFound = 0;
        
        try{
        if(Float.parseFloat(CurrentPrimeValue.getText()) > 0 || "".equals(CurrentPrimeValue.getText())){
           CurrentPrimeValue.setEditable(false);
        }
        if(Float.parseFloat(CurrentPrimeValue.getText()) <= 0 || "".equals(CurrentPrimeValue.getText()) ){
             jPane.showMessageDialog(rootPane, "Please input a value greater than 0 for current prime rate.");
         }else if(Integer.parseInt(LoanNumberValue.getText()) <= 0 || "".equals(LoanNumberValue.getText()) ){
             jPane.showMessageDialog(rootPane, "Please input a value greater than 0 for the loan number.");
         }else if(Integer.parseInt(LoanAmountValue.getText()) <= 0 || Integer.parseInt(LoanAmountValue.getText()) > 100000){
             jPane.showMessageDialog(rootPane, "Please input a value greater than 0 and less than 100000 for the loan amount.");
         }else if("".equals(LastNameValue.getText())){
             jPane.showMessageDialog(rootPane, "Please input a Last Name.");
         } else if (containsDigits(LastNameValue.getText())) {
             jPane.showMessageDialog(rootPane, "Last Name: Characters Only!");
        return;
         }else{
                try{
                    for(int i = 0; i<list.length; i++){
                    if (list[i].getLoanNumber() == Integer.parseInt(LoanNumberValue.getText())){
                        jPane.showMessageDialog(rootPane, "Loan number already exists. Please input a different number.");
                        lNumFound = 1;
                    }
                }
                //Checking for distinct loan number values.
                }catch(NullPointerException npe){
                }
                if(lNumFound != 1){
                    if (LoanTypeComboBox.getSelectedItem() == "Personal"){
                       if(TermComboBox.getSelectedItem() == "Short Term"){
                           list[current] = new PersonalLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),SHORT_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else if(TermComboBox.getSelectedItem() == "Medium Term"){
                           list[current] = new PersonalLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),MEDIUM_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else if(TermComboBox.getSelectedItem() == "Long Term"){
                           list[current] = new PersonalLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),LONG_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else{
                           jPane.showMessageDialog(rootPane, "Please select a term option.");
                       }
                   }else if(LoanTypeComboBox.getSelectedItem() == "Business"){
                       if(TermComboBox.getSelectedItem() == "Short Term"){
                           list[current] = new BusinessLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),SHORT_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else if(TermComboBox.getSelectedItem() == "Medium Term"){
                           list[current] = new BusinessLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),MEDIUM_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else if(TermComboBox.getSelectedItem() == "Long Term"){
                           list[current] = new BusinessLoan(Integer.parseInt(LoanNumberValue.getText()),LastNameValue.getText(), Integer.parseInt(LoanAmountValue.getText()),LONG_TERM,Float.parseFloat(CurrentPrimeValue.getText()));
                           current++;
                       }else{
                           jPane.showMessageDialog(rootPane, "Please select a term.");
                       }
                   }else{
                       jPane.showMessageDialog(rootPane, "Please select a loan type.");
                   }
                }
         }
        }catch(NumberFormatException nfe){
            jPane.showMessageDialog(rootPane, "Please input  number/details in the necessary field.");
        }
        
    }//GEN-LAST:event_SaveBttnActionPerformed

    private void ViewComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewComboBoxActionPerformed

    private void TermComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TermComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanApp().setVisible(true);
            }
        });
    }
    
    private javax.swing.JOptionPane jPane;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBttn;
    private javax.swing.JTextField CurrentPrimeValue;
    private javax.swing.JButton ExitBttn;
    private javax.swing.JButton GoBttn;
    private javax.swing.JTextField LastNameValue;
    private javax.swing.JTextField LoanAmountValue;
    private javax.swing.JTextField LoanNumberValue;
    private javax.swing.JComboBox<String> LoanTypeComboBox;
    private javax.swing.JButton SaveBttn;
    private javax.swing.JComboBox<String> TermComboBox;
    private javax.swing.JTextArea TextAreaValue;
    private javax.swing.JComboBox<String> ViewComboBox;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}